apiVersion: v1
entries:
  flowable:
  - apiVersion: v1
    appVersion: 6.5.0
    created: "2020-02-19T12:22:38.000702862Z"
    dependencies:
    - condition: nginx-ingress.enabled
      name: nginx-ingress
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.3.1
    description: A Flowable Helm chart for Kubernetes
    digest: c1fbb82fb88a7f4333b73ca98dd65c3a83fe58deae3bff8dc64055be0474e86c
    home: https://flowable.org
    icon: https://flowable.org/docs/img/logo.png
    name: flowable
    urls:
    - flowable-6.5.0.tgz
    version: 6.5.0
  nginx-ingress:
  - apiVersion: v1
    appVersion: 0.22.0
    created: "2020-02-19T12:22:38.001789615Z"
    description: An nginx Ingress controller that uses ConfigMap to store the nginx
      configuration.
    digest: f2afafb094da3f25de03cfd9796fb932abeaa627e2ea6c8b0e0aa94d2ce53d83
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    maintainers:
    - email: jack.zampolin@gmail.com
      name: jackzampolin
    - email: mgoodness@gmail.com
      name: mgoodness
    name: nginx-ingress
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - charts/nginx-ingress-1.3.1.tgz
    version: 1.3.1
generated: "2020-02-19T12:22:37.996475391Z"
